name: Build Docker - Release
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-docker:
    name: Build Docker - Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@6520a2d2cb6db42c90c297c8025839c98e531268
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32
      - name: Login to DockerHub
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547
        with:
          context: ./.github/eosjs-ci
          file: ./.github/eosjs-ci/Dockerfile
          pull: true
          push: true
          no-cache: true
          build-args: |
            EOSBRANCH=release_2.1.x
            CDTBRANCH=release_1.8.x
          tags: |
            eosio/eosjs-ci:release_22.0.x
            eosio/eosjs-ci:${{ github.sha }}
