name: Build Docker
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-18.04
    steps:
      - name: Check for Docker Credentials
        id: check_token
        run: echo ::set-output name=token_exists::${HAS_SECRET}
        env:
          HAS_SECRET: ${{ secrets.DOCKERHUB_TOKEN != null }}
      - name: Checkout
        uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
        with:
          token: ${{ github.token }}
      - name: Set up QEMU
        if: ${{ steps.check_token.outputs.token_exists == 'false' }}
        uses: docker/setup-qemu-action@6520a2d2cb6db42c90c297c8025839c98e531268
      - name: Set up Docker Buildx
        if: ${{ steps.check_token.outputs.token_exists == 'false' }}
        uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32
      - name: Login to DockerHub
        if: ${{ steps.check_token.outputs.token_exists == 'false' }}
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: ${{ steps.check_token.outputs.token_exists == 'false' }}
        uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547
        with:
          context: .
          file: ./.github/eosjs-ci/Dockerfile
          tags: |
            eosio/eosjs-ci:latest
            eosio/eosjs-ci:${GITHUB_SHA}
