name: Build Docker - Release
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-docker:
    name: Build Docker - Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e
      - name: Login to DockerHub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f
        with:
          context: ./.github/eosjs-ci
          file: ./.github/eosjs-ci/Dockerfile
          pull: true
          push: true
          no-cache: true
          build-args: |
            EOSBRANCH=release_2.1.x
            CDTBRANCH=release_1.8.x
          tags: |
            eosio/eosjs-ci:release_22.0.x
            eosio/eosjs-ci:${{ github.sha }}
