name: Integration Test - Release
on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  integration-test:
    name: Integration Test - Release
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@aa759c6c94d3800c55b8601f21ba4b2371704cb7
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Test Types
        run: |
          yarn test-types
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          spec: cypress/integration/index.spec.js
    services:
      nodeos:
        image: eosio/eosjs-ci:release_22.0.x

        ports:
          - 8888:8888
          - 9876:9876
