name: Publish
on:
  release:
    types: [published]

jobs:
  publish-release:
    if: "!github.event.release.prerelease"
    name: Publish Release
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.14.1]
    steps:
      - name: Checkout
        uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Test Types
        run: |
          yarn test-types
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@89161930792c0050baeba2737caa058c395ecfcb
        with:
          spec: cypress/integration/index.spec.js
      - name: Publish Release
        run: |
          . ./scripts/publish-utils.sh
          setup_git
          ensure_version_match
          git commit -a -m "Updating version [skip ci]" --allow-empty
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    services:
      nodeos:
        image: eosio/eosjs-ci:release_22.0.x

        ports:
          - 8888:8888
          - 9876:9876


  publish-rc:
    if: "github.event.release.prerelease"
    name: Publish RC
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.14.1]
    steps:
      - name: Checkout
        uses: actions/checkout@f90c7b395dac7c5a277c1a6d93d5057c1cddb74e
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node
      - name: Test Types
        run: |
          yarn test-types
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@89161930792c0050baeba2737caa058c395ecfcb
        with:
          spec: cypress/integration/index.spec.js
      - name: Publish RC
        run: |
          . ./scripts/publish-utils.sh
          setup_git
          ensure_version_match
          git commit -a -m "Updating version [skip ci]" --allow-empty
          npm publish --access public --tag RC
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    services:
      nodeos:
        image: eosio/eosjs-ci:release_22.0.x

        ports:
          - 8888:8888
          - 9876:9876
